networks:
  mgmt:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-0
    ipam:
      config:
      - subnet: 172.30.0.0/24
  xrd-1-xrd-2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-1
    ipam:
      config:
      - subnet: 10.1.2.0/24
  xrd-1-xrd-3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-2
    ipam:
      config:
      - subnet: 10.1.3.0/24
  xrd-2-xrd-4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-3
    ipam:
      config:
      - subnet: 10.2.4.0/24
  xrd-3-xrd-4-1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-7
    ipam:
      config:
      - subnet: 10.3.4.0/30
  xrd-3-xrd-4-2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-8
    ipam:
      config:
      - subnet: 10.3.4.4/30
  xrd-3-xrd-4-3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-9
    ipam:
      config:
      - subnet: 10.3.4.8/30
  xrd-3-xrd-4-4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-10
    ipam:
      config:
      - subnet: 10.3.4.12/30
  xrd-3-xrd-4-5:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-11
    ipam:
      config:
      - subnet: 10.3.4.16/30
  xrd-3-xrd-4-6:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-12
    ipam:
      config:
      - subnet: 10.3.4.20/30
  xrd-3-xrd-4-7:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-13
    ipam:
      config:
      - subnet: 10.3.4.24/30
  xrd-3-xrd-5-1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-14
    ipam:
      config:
      - subnet: 10.3.5.0/30
  xrd-3-xrd-5-2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-15
    ipam:
      config:
      - subnet: 10.3.5.4/30
  xrd-3-xrd-5-3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-16
    ipam:
      config:
      - subnet: 10.3.5.8/30
  xrd-3-xrd-5-4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-17
    ipam:
      config:
      - subnet: 10.3.5.12/30
  xrd-3-xrd-5-5:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-18
    ipam:
      config:
      - subnet: 10.3.5.16/30
  xrd-3-xrd-5-6:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-19
    ipam:
      config:
      - subnet: 10.3.5.20/30
  xrd-3-xrd-5-7:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-20
    ipam:
      config:
      - subnet: 10.3.5.24/30
  xrd-4-xrd-6-1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-21
    ipam:
      config:
      - subnet: 10.4.6.0/30
  xrd-4-xrd-6-2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-22
    ipam:
      config:
      - subnet: 10.4.6.4/30
  xrd-4-xrd-6-3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-23
    ipam:
      config:
      - subnet: 10.4.6.8/30
  xrd-4-xrd-6-4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-24
    ipam:
      config:
      - subnet: 10.4.6.12/30
  xrd-4-xrd-6-5:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-25
    ipam:
      config:
      - subnet: 10.4.6.16/30
  xrd-4-xrd-6-6:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-26
    ipam:
      config:
      - subnet: 10.4.6.20/30
  xrd-4-xrd-6-7:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-27
    ipam:
      config:
      - subnet: 10.4.6.24/30
  xrd-5-xrd-6-1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-28
    ipam:
      config:
      - subnet: 10.5.6.0/30
  xrd-5-xrd-6-2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-29
    ipam:
      config:
      - subnet: 10.5.6.4/30
  xrd-5-xrd-6-3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-30
    ipam:
      config:
      - subnet: 10.5.6.8/30
  xrd-5-xrd-6-4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-31
    ipam:
      config:
      - subnet: 10.5.6.12/30
  xrd-5-xrd-6-5:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-32
    ipam:
      config:
      - subnet: 10.5.6.16/30
  xrd-5-xrd-7:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-5
    ipam:
      config:
      - subnet: 10.5.7.0/24
  xrd-6-xrd-8:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-6
    ipam:
      config:
      - subnet: 10.6.8.0/24
  xrd-7-xrd-8:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-4
    ipam:
      config:
      - subnet: 10.7.8.0/24
services:
  xrd-1:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-1
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-20,xr_name=Gi0/0/0/0,chksum;linux:xr-10,xr_name=Gi0/0/0/1,chksum
      XR_MGMT_INTERFACES: linux:xr-00,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.8.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.2
      xrd-1-xrd-2:
        ipv4_address: 10.1.2.1
      xrd-1-xrd-3:
        ipv4_address: 10.1.3.1
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-1-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-1:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-2:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-2
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-30,xr_name=Gi0/0/0/0,chksum;linux:xr-10,xr_name=Gi0/0/0/1,chksum
      XR_MGMT_INTERFACES: linux:xr-00,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.8.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.3
      xrd-1-xrd-2:
        ipv4_address: 10.1.2.2
      xrd-2-xrd-4:
        ipv4_address: 10.2.4.2
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-2-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-2:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-3:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-3
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-20,xr_name=Gi0/0/0/0,chksum;linux:xr-70,xr_name=Gi0/0/0/11,chksum;linux:xr-80,xr_name=Gi0/0/0/12,chksum;linux:xr-90,xr_name=Gi0/0/0/13,chksum;linux:xr-100,xr_name=Gi0/0/0/14,chksum;linux:xr-110,xr_name=Gi0/0/0/15,chksum;linux:xr-120,xr_name=Gi0/0/0/16,chksum;linux:xr-130,xr_name=Gi0/0/0/17,chksum;linux:xr-140,xr_name=Gi0/0/0/21,chksum;linux:xr-150,xr_name=Gi0/0/0/22,chksum;linux:xr-160,xr_name=Gi0/0/0/23,chksum;linux:xr-170,xr_name=Gi0/0/0/24,chksum;linux:xr-180,xr_name=Gi0/0/0/25,chksum;linux:xr-190,xr_name=Gi0/0/0/26,chksum;linux:xr-200,xr_name=Gi0/0/0/27,chksum
      XR_MGMT_INTERFACES: linux:xr-00,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.8.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.4
      xrd-1-xrd-3:
        ipv4_address: 10.1.3.3
      xrd-3-xrd-4-1:
        ipv4_address: 10.3.4.1
      xrd-3-xrd-4-2:
        ipv4_address: 10.3.4.5
      xrd-3-xrd-4-3:
        ipv4_address: 10.3.4.9
      xrd-3-xrd-4-4:
        ipv4_address: 10.3.4.13
      xrd-3-xrd-4-5:
        ipv4_address: 10.3.4.17
      xrd-3-xrd-4-6:
        ipv4_address: 10.3.4.21
      xrd-3-xrd-4-7:
        ipv4_address: 10.3.4.25
      xrd-3-xrd-5-1:
        ipv4_address: 10.3.5.1
      xrd-3-xrd-5-2:
        ipv4_address: 10.3.5.5
      xrd-3-xrd-5-3:
        ipv4_address: 10.3.5.9
      xrd-3-xrd-5-4:
        ipv4_address: 10.3.5.13
      xrd-3-xrd-5-5:
        ipv4_address: 10.3.5.17
      xrd-3-xrd-5-6:
        ipv4_address: 10.3.5.21
      xrd-3-xrd-5-7:
        ipv4_address: 10.3.5.25
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-3-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-3:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-4:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-4
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-30,xr_name=Gi0/0/0/0,chksum;linux:xr-70,xr_name=Gi0/0/0/11,chksum;linux:xr-80,xr_name=Gi0/0/0/12,chksum;linux:xr-90,xr_name=Gi0/0/0/13,chksum;linux:xr-100,xr_name=Gi0/0/0/14,chksum;linux:xr-110,xr_name=Gi0/0/0/15,chksum;linux:xr-120,xr_name=Gi0/0/0/16,chksum;linux:xr-130,xr_name=Gi0/0/0/17,chksum;linux:xr-210,xr_name=Gi0/0/0/21,chksum;linux:xr-220,xr_name=Gi0/0/0/22,chksum;linux:xr-230,xr_name=Gi0/0/0/23,chksum;linux:xr-240,xr_name=Gi0/0/0/24,chksum;linux:xr-250,xr_name=Gi0/0/0/25,chksum;linux:xr-260,xr_name=Gi0/0/0/26,chksum;linux:xr-270,xr_name=Gi0/0/0/27,chksum
      XR_MGMT_INTERFACES: linux:xr-00,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.8.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.5
      xrd-2-xrd-4:
        ipv4_address: 10.2.4.4
      xrd-3-xrd-4-1:
        ipv4_address: 10.3.4.2
      xrd-3-xrd-4-2:
        ipv4_address: 10.3.4.6
      xrd-3-xrd-4-3:
        ipv4_address: 10.3.4.10
      xrd-3-xrd-4-4:
        ipv4_address: 10.3.4.14
      xrd-3-xrd-4-5:
        ipv4_address: 10.3.4.18
      xrd-3-xrd-4-6:
        ipv4_address: 10.3.4.22
      xrd-3-xrd-4-7:
        ipv4_address: 10.3.4.26
      xrd-4-xrd-6-1:
        ipv4_address: 10.4.6.1
      xrd-4-xrd-6-2:
        ipv4_address: 10.4.6.5
      xrd-4-xrd-6-3:
        ipv4_address: 10.4.6.9
      xrd-4-xrd-6-4:
        ipv4_address: 10.4.6.13
      xrd-4-xrd-6-5:
        ipv4_address: 10.4.6.17
      xrd-4-xrd-6-6:
        ipv4_address: 10.4.6.21
      xrd-4-xrd-6-7:
        ipv4_address: 10.4.6.25
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-4-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-4:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-5:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-5
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-50,xr_name=Gi0/0/0/0,chksum;linux:xr-280,xr_name=Gi0/0/0/11,chksum;linux:xr-290,xr_name=Gi0/0/0/12,chksum;linux:xr-300,xr_name=Gi0/0/0/13,chksum;linux:xr-310,xr_name=Gi0/0/0/14,chksum;linux:xr-320,xr_name=Gi0/0/0/15,chksum;linux:xr-140,xr_name=Gi0/0/0/21,chksum;linux:xr-150,xr_name=Gi0/0/0/22,chksum;linux:xr-160,xr_name=Gi0/0/0/23,chksum;linux:xr-170,xr_name=Gi0/0/0/24,chksum;linux:xr-180,xr_name=Gi0/0/0/25,chksum;linux:xr-190,xr_name=Gi0/0/0/26,chksum;linux:xr-200,xr_name=Gi0/0/0/27,chksum
      XR_MGMT_INTERFACES: linux:xr-00,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.8.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.6
      xrd-3-xrd-5-1:
        ipv4_address: 10.3.5.2
      xrd-3-xrd-5-2:
        ipv4_address: 10.3.5.6
      xrd-3-xrd-5-3:
        ipv4_address: 10.3.5.10
      xrd-3-xrd-5-4:
        ipv4_address: 10.3.5.14
      xrd-3-xrd-5-5:
        ipv4_address: 10.3.5.18
      xrd-3-xrd-5-6:
        ipv4_address: 10.3.5.22
      xrd-3-xrd-5-7:
        ipv4_address: 10.3.5.26
      xrd-5-xrd-6-1:
        ipv4_address: 10.5.6.1
      xrd-5-xrd-6-2:
        ipv4_address: 10.5.6.5
      xrd-5-xrd-6-3:
        ipv4_address: 10.5.6.9
      xrd-5-xrd-6-4:
        ipv4_address: 10.5.6.13
      xrd-5-xrd-6-5:
        ipv4_address: 10.5.6.17
      xrd-5-xrd-7:
        ipv4_address: 10.5.7.5
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-5-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-5:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-6:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-6
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-60,xr_name=Gi0/0/0/0,chksum;linux:xr-280,xr_name=Gi0/0/0/11,chksum;linux:xr-290,xr_name=Gi0/0/0/12,chksum;linux:xr-300,xr_name=Gi0/0/0/13,chksum;linux:xr-310,xr_name=Gi0/0/0/14,chksum;linux:xr-320,xr_name=Gi0/0/0/15,chksum;linux:xr-210,xr_name=Gi0/0/0/21,chksum;linux:xr-220,xr_name=Gi0/0/0/22,chksum;linux:xr-230,xr_name=Gi0/0/0/23,chksum;linux:xr-240,xr_name=Gi0/0/0/24,chksum;linux:xr-250,xr_name=Gi0/0/0/25,chksum;linux:xr-260,xr_name=Gi0/0/0/26,chksum;linux:xr-270,xr_name=Gi0/0/0/27,chksum
      XR_MGMT_INTERFACES: linux:xr-00,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.8.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.7
      xrd-4-xrd-6-1:
        ipv4_address: 10.4.6.2
      xrd-4-xrd-6-2:
        ipv4_address: 10.4.6.6
      xrd-4-xrd-6-3:
        ipv4_address: 10.4.6.10
      xrd-4-xrd-6-4:
        ipv4_address: 10.4.6.14
      xrd-4-xrd-6-5:
        ipv4_address: 10.4.6.18
      xrd-4-xrd-6-6:
        ipv4_address: 10.4.6.22
      xrd-4-xrd-6-7:
        ipv4_address: 10.4.6.26
      xrd-5-xrd-6-1:
        ipv4_address: 10.5.6.2
      xrd-5-xrd-6-2:
        ipv4_address: 10.5.6.6
      xrd-5-xrd-6-3:
        ipv4_address: 10.5.6.10
      xrd-5-xrd-6-4:
        ipv4_address: 10.5.6.14
      xrd-5-xrd-6-5:
        ipv4_address: 10.5.6.18
      xrd-6-xrd-8:
        ipv4_address: 10.6.8.6
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-6-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-6:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-7:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-7
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-50,xr_name=Gi0/0/0/0,chksum;linux:xr-40,xr_name=Gi0/0/0/1,chksum
      XR_MGMT_INTERFACES: linux:xr-00,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.8.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.8
      xrd-5-xrd-7:
        ipv4_address: 10.5.7.7
      xrd-7-xrd-8:
        ipv4_address: 10.7.8.7
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-7-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-7:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-8:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-8
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-60,xr_name=Gi0/0/0/0,chksum;linux:xr-40,xr_name=Gi0/0/0/1,chksum
      XR_MGMT_INTERFACES: linux:xr-00,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.8.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.9
      xrd-6-xrd-8:
        ipv4_address: 10.6.8.8
      xrd-7-xrd-8:
        ipv4_address: 10.7.8.8
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-8-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-8:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
version: '2.4'
volumes:
  xrd-1:
    name: xrd-1
  xrd-2:
    name: xrd-2
  xrd-3:
    name: xrd-3
  xrd-4:
    name: xrd-4
  xrd-5:
    name: xrd-5
  xrd-6:
    name: xrd-6
  xrd-7:
    name: xrd-7
  xrd-8:
    name: xrd-8
